{{- if not .Values.centauri.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cc1-notifier.fullname" . }}
  labels:
    {{- include "cc1-notifier.labels" . | nindent 4 }}
type: Opaque
stringData:
  MAINBOARD_ID: {{ .Values.centauri.mainboardId | quote }}
  DISCORD_WEBHOOK_URL: {{ .Values.centauri.discordWebhookUrl | quote }}
{{- end }}
